name: counter_mobx
description: Contador utilizando MobX.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  mobx_codegen: ^0.4.1

flutter:
  uses-material-design: true
